name: CI
on:
  pull_request: ~
  push: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          stack install hlint weeder
          
      - name: Run sanity check
        run: |
          ./Shakefile.hs sanity

      - name: Run tests
        run: |
          stack test
