name: CI
on:
  pull_request: ~
  push: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-lts-10.4
          path: |
            ~/.local/bin/hlint
            ~/.local/bin/weeder
            ~/.local/bin/data/

      - name: Install tools
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          stack install hlint weeder
          
      - name: Run sanity check
        run: |
          ./Shakefile.hs sanity

      - name: Run tests
        run: |
          stack test
